package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adminId;
     private UserAccounts userAccounts;

    public Admin() {
    }

    public Admin(UserAccounts userAccounts) {
       this.userAccounts = userAccounts;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public UserAccounts getUserAccounts() {
        return this.userAccounts;
    }
    
    public void setUserAccounts(UserAccounts userAccounts) {
        this.userAccounts = userAccounts;
    }




}


