package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1



/**
 * Banner generated by hbm2java
 */
public class Banner  implements java.io.Serializable {


     private Integer bannerId;
     private byte[] img;
     private String name;
     private String description;

    public Banner() {
    }

    public Banner(byte[] img, String name, String description) {
       this.img = img;
       this.name = name;
       this.description = description;
    }
   
    public Integer getBannerId() {
        return this.bannerId;
    }
    
    public void setBannerId(Integer bannerId) {
        this.bannerId = bannerId;
    }
    public byte[] getImg() {
        return this.img;
    }
    
    public void setImg(byte[] img) {
        this.img = img;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


