package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer cartId;
     private Menu menu;
     private UserAccounts userAccounts;
     private int quantity;

    public Cart() {
    }

    public Cart(Menu menu, UserAccounts userAccounts, int quantity) {
       this.menu = menu;
       this.userAccounts = userAccounts;
       this.quantity = quantity;
    }
   
    public Integer getCartId() {
        return this.cartId;
    }
    
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public UserAccounts getUserAccounts() {
        return this.userAccounts;
    }
    
    public void setUserAccounts(UserAccounts userAccounts) {
        this.userAccounts = userAccounts;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


