package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ContactQuestions generated by hbm2java
 */
public class ContactQuestions  implements java.io.Serializable {


     private Integer contactId;
     private UserAccounts userAccounts;
     private String subject;
     private String question;
     private Date createdAt;

    public ContactQuestions() {
    }

    public ContactQuestions(UserAccounts userAccounts, String subject, String question, Date createdAt) {
       this.userAccounts = userAccounts;
       this.subject = subject;
       this.question = question;
       this.createdAt = createdAt;
    }
   
    public Integer getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }
    public UserAccounts getUserAccounts() {
        return this.userAccounts;
    }
    
    public void setUserAccounts(UserAccounts userAccounts) {
        this.userAccounts = userAccounts;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


