package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer itemId;
     private byte[] img;
     private String name;
     private BigDecimal price;
     private String category;
     private String active;
     private Set<Transactionitems> transactionitemses = new HashSet<Transactionitems>(0);
     private Set<Specialoffer> specialoffers = new HashSet<Specialoffer>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);

    public Menu() {
    }

	
    public Menu(byte[] img, String name, BigDecimal price, String category, String active) {
        this.img = img;
        this.name = name;
        this.price = price;
        this.category = category;
        this.active = active;
    }
    public Menu(byte[] img, String name, BigDecimal price, String category, String active, Set<Transactionitems> transactionitemses, Set<Specialoffer> specialoffers, Set<Cart> carts) {
       this.img = img;
       this.name = name;
       this.price = price;
       this.category = category;
       this.active = active;
       this.transactionitemses = transactionitemses;
       this.specialoffers = specialoffers;
       this.carts = carts;
    }
   
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public byte[] getImg() {
        return this.img;
    }
    
    public void setImg(byte[] img) {
        this.img = img;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }
    public Set<Transactionitems> getTransactionitemses() {
        return this.transactionitemses;
    }
    
    public void setTransactionitemses(Set<Transactionitems> transactionitemses) {
        this.transactionitemses = transactionitemses;
    }
    public Set<Specialoffer> getSpecialoffers() {
        return this.specialoffers;
    }
    
    public void setSpecialoffers(Set<Specialoffer> specialoffers) {
        this.specialoffers = specialoffers;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }




}


