package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Outlet generated by hbm2java
 */
public class Outlet  implements java.io.Serializable {


     private Integer outletId;
     private String outletName;
     private String address;
     private int serviceArea;
     private Set<Transactions> transactionses = new HashSet<Transactions>(0);
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Outlet() {
    }

	
    public Outlet(String outletName, String address, int serviceArea) {
        this.outletName = outletName;
        this.address = address;
        this.serviceArea = serviceArea;
    }
    public Outlet(String outletName, String address, int serviceArea, Set<Transactions> transactionses, Set<Reservation> reservations) {
       this.outletName = outletName;
       this.address = address;
       this.serviceArea = serviceArea;
       this.transactionses = transactionses;
       this.reservations = reservations;
    }
   
    public Integer getOutletId() {
        return this.outletId;
    }
    
    public void setOutletId(Integer outletId) {
        this.outletId = outletId;
    }
    public String getOutletName() {
        return this.outletName;
    }
    
    public void setOutletName(String outletName) {
        this.outletName = outletName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getServiceArea() {
        return this.serviceArea;
    }
    
    public void setServiceArea(int serviceArea) {
        this.serviceArea = serviceArea;
    }
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


