package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer reserveId;
     private Outlet outlet;
     private UserAccounts userAccounts;
     private String customerName;
     private String phoneNumber;
     private Date reservedDate;
     private Date reservedTime;
     private int durationHours;
     private Date dateOnReservation;
     private String status;

    public Reservation() {
    }

    public Reservation(Outlet outlet, UserAccounts userAccounts, String customerName, String phoneNumber, Date reservedDate, Date reservedTime, int durationHours, Date dateOnReservation, String status) {
       this.outlet = outlet;
       this.userAccounts = userAccounts;
       this.customerName = customerName;
       this.phoneNumber = phoneNumber;
       this.reservedDate = reservedDate;
       this.reservedTime = reservedTime;
       this.durationHours = durationHours;
       this.dateOnReservation = dateOnReservation;
       this.status = status;
    }
   
    public Integer getReserveId() {
        return this.reserveId;
    }
    
    public void setReserveId(Integer reserveId) {
        this.reserveId = reserveId;
    }
    public Outlet getOutlet() {
        return this.outlet;
    }
    
    public void setOutlet(Outlet outlet) {
        this.outlet = outlet;
    }
    public UserAccounts getUserAccounts() {
        return this.userAccounts;
    }
    
    public void setUserAccounts(UserAccounts userAccounts) {
        this.userAccounts = userAccounts;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Date getReservedDate() {
        return this.reservedDate;
    }
    
    public void setReservedDate(Date reservedDate) {
        this.reservedDate = reservedDate;
    }
    public Date getReservedTime() {
        return this.reservedTime;
    }
    
    public void setReservedTime(Date reservedTime) {
        this.reservedTime = reservedTime;
    }
    public int getDurationHours() {
        return this.durationHours;
    }
    
    public void setDurationHours(int durationHours) {
        this.durationHours = durationHours;
    }
    public Date getDateOnReservation() {
        return this.dateOnReservation;
    }
    
    public void setDateOnReservation(Date dateOnReservation) {
        this.dateOnReservation = dateOnReservation;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


