package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private Integer transactionId;
     private Outlet outlet;
     private UserAccounts userAccounts;
     private Date transactionDate;
     private BigDecimal totalAmount;
     private String address;
     private String paymentMethod;
     private Set<Transactionitems> transactionitemses = new HashSet<Transactionitems>(0);

    public Transactions() {
    }

	
    public Transactions(Outlet outlet, UserAccounts userAccounts, Date transactionDate, BigDecimal totalAmount, String address, String paymentMethod) {
        this.outlet = outlet;
        this.userAccounts = userAccounts;
        this.transactionDate = transactionDate;
        this.totalAmount = totalAmount;
        this.address = address;
        this.paymentMethod = paymentMethod;
    }
    public Transactions(Outlet outlet, UserAccounts userAccounts, Date transactionDate, BigDecimal totalAmount, String address, String paymentMethod, Set<Transactionitems> transactionitemses) {
       this.outlet = outlet;
       this.userAccounts = userAccounts;
       this.transactionDate = transactionDate;
       this.totalAmount = totalAmount;
       this.address = address;
       this.paymentMethod = paymentMethod;
       this.transactionitemses = transactionitemses;
    }
   
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }
    public Outlet getOutlet() {
        return this.outlet;
    }
    
    public void setOutlet(Outlet outlet) {
        this.outlet = outlet;
    }
    public UserAccounts getUserAccounts() {
        return this.userAccounts;
    }
    
    public void setUserAccounts(UserAccounts userAccounts) {
        this.userAccounts = userAccounts;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Set<Transactionitems> getTransactionitemses() {
        return this.transactionitemses;
    }
    
    public void setTransactionitemses(Set<Transactionitems> transactionitemses) {
        this.transactionitemses = transactionitemses;
    }




}


