package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Transactionitems generated by hbm2java
 */
public class Transactionitems  implements java.io.Serializable {


     private Integer transactionItemId;
     private Menu menu;
     private Transactions transactions;
     private String itemName;
     private int quantity;
     private BigDecimal price;

    public Transactionitems() {
    }

    public Transactionitems(Menu menu, Transactions transactions, String itemName, int quantity, BigDecimal price) {
       this.menu = menu;
       this.transactions = transactions;
       this.itemName = itemName;
       this.quantity = quantity;
       this.price = price;
    }
   
    public Integer getTransactionItemId() {
        return this.transactionItemId;
    }
    
    public void setTransactionItemId(Integer transactionItemId) {
        this.transactionItemId = transactionItemId;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public Transactions getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Transactions transactions) {
        this.transactions = transactions;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


