package model;
// Generated Sep 29, 2024 6:26:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserAccounts generated by hbm2java
 */
public class UserAccounts  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String email;
     private String userPnum;
     private String password;
     private Set<ContactQuestions> contactQuestionses = new HashSet<ContactQuestions>(0);
     private Set<Reservation> reservations = new HashSet<Reservation>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Transactions> transactionses = new HashSet<Transactions>(0);
     private Set<Admin> admins = new HashSet<Admin>(0);

    public UserAccounts() {
    }

	
    public UserAccounts(String username, String email, String userPnum, String password) {
        this.username = username;
        this.email = email;
        this.userPnum = userPnum;
        this.password = password;
    }
    public UserAccounts(String username, String email, String userPnum, String password, Set<ContactQuestions> contactQuestionses, Set<Reservation> reservations, Set<Cart> carts, Set<Transactions> transactionses, Set<Admin> admins) {
       this.username = username;
       this.email = email;
       this.userPnum = userPnum;
       this.password = password;
       this.contactQuestionses = contactQuestionses;
       this.reservations = reservations;
       this.carts = carts;
       this.transactionses = transactionses;
       this.admins = admins;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserPnum() {
        return this.userPnum;
    }
    
    public void setUserPnum(String userPnum) {
        this.userPnum = userPnum;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<ContactQuestions> getContactQuestionses() {
        return this.contactQuestionses;
    }
    
    public void setContactQuestionses(Set<ContactQuestions> contactQuestionses) {
        this.contactQuestionses = contactQuestionses;
    }
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }
    public Set<Admin> getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set<Admin> admins) {
        this.admins = admins;
    }




}


